### ISSUE TITLE
blank link §

### ISSUE THREAD

**Issue by dark161** [noob-hackers/grabcam#1]
+] Choose a Port Forwarding option: 1
[+] Choose subdomain? (Default: [Y/n] ): y
[+] Subdomain: (Default: grabcam609 ): 
[+] Starting Serveo...
[+] Starting php server... (localhost:3333)
[+] Direct link: 

[*] Waiting targets, Press Ctrl + C to exit...

**Comment by Dexz0** [comment]
same issue, dont show the Direct link
