### ISSUE TITLE
no link\нет ссылки

### ISSUE THREAD

**Issue by Joke-del** [noob-hackers/grabcam#28]
Why isn't the link displayed in the "Direct Link" line?\Почему в строке "Direct Link" не выводится ссылка?
![IMG_20210203_170411](https://user-images.githubusercontent.com/72986398/106766541-a6f6d100-6642-11eb-99a5-ca51a1671a20.jpg)

**Comment by RAVIKASHYAP05** [comment]
Same problem

**Comment by RAVIKASHYAP05** [comment]
Direct link Ngrok se Copy karo..

**Comment by VBPROGER** [comment]
[127.0.0.1](http://127.0.0.1:4040/status)
You can find link here. (first start it)

**Comment by VBPROGER** [comment]
Also try this [link](http://localhost:3333) (if you use `serveo.net`).
