### ISSUE TITLE
chmod: cannot access 'ngrok': No such file or director

### ISSUE THREAD

**Issue by newsdelhi10** [noob-hackers/grabcam#37]
Grabcam how to send link on victim

**Comment by FadilMohad** [comment]
How to fix it

**Comment by users2583** [comment]
Install ngrok first
`pkg install zip wget -y`
`wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip
`
`unzip ngrok-stable-linux-arm.zip`
`chmod +x ngrok`

Now open [Ngrok](https://ngrok.io) 
Get your token and add here in this command `./ngrok authtoken YOUR_AUTH_TOKEN_HERE`

Keep hotspot on, and here you go....
